# Generated by Django 5.1.5 on 2025-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='next_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
