# Generated by Django 5.1.5 on 2025-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Credit', 'Credit')], max_length=50),
        ),
    ]
