# Generated by Django 5.1.5 on 2025-02-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_appointment_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_followup',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
