# Generated by Django 5.1.5 on 2025-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_appointment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresults',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labservice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='nursingnotes',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pharmacypurchase',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DoctorNotes',
        ),
        migrations.DeleteModel(
            name='LabResults',
        ),
        migrations.DeleteModel(
            name='LabService',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='NursingNotes',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='PharmacyPurchase',
        ),
        migrations.DeleteModel(
            name='Vitals',
        ),
    ]
