# Generated by Django 5.1.5 on 2025-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_doctor_follow_up_days_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='follow_up_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Credit', 'Credit')], max_length=50),
        ),
    ]
