# Generated by Django 5.1.5 on 2025-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_doctor_follow_up_days_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
